# Generated by Django 3.1.12 on 2021-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_ban',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
