# Generated by Django 3.1.10 on 2021-05-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0002_caracteristique_caracteristiqueproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristique',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('champs multiple', 'Champs multiple'), ('texte', 'Texte'), ('date', 'Date')], default='texte', max_length=20),
        ),
    ]
