# Generated by Django 3.1.10 on 2021-05-26 13:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0003_caracteristique_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristique',
            name='champs_multiple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='select',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='texte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
