# Generated by Django 3.1.11 on 2021-05-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0006_auto_20210527_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristiqueproduit',
            old_name='texte_valeur',
            new_name='texteAndselect_valeur',
        ),
        migrations.RemoveField(
            model_name='caracteristiqueproduit',
            name='select_valeur',
        ),
    ]
