# Generated by Django 3.1.11 on 2021-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0007_auto_20210527_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristiqueproduit',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
