# Generated by Django 3.1.11 on 2021-05-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0008_caracteristiqueproduit_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='critere',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fonctionnel',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='version',
        ),
        migrations.AlterField(
            model_name='caracteristiqueproduit',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestionDeProduits.produit'),
            preserve_default=False,
        ),
    ]
