# Generated by Django 3.1.12 on 2021-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0010_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('unpublished', 'UNPUBLISHED')], default='published', max_length=30),
        ),
    ]
