# Generated by Django 3.1.12 on 2021-06-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0012_produit_deadline_unpublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitSignalé',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDeProduits.produit')),
            ],
        ),
    ]
