# Generated by Django 3.1.12 on 2021-06-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0013_produitsignalé'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProduitSignalé',
            new_name='ProduitsSignalé',
        ),
    ]
