# Generated by Django 3.1.12 on 2021-06-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeProduits', '0014_auto_20210607_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitssignalé',
            old_name='created_at',
            new_name='reported_at',
        ),
    ]
